import './globals.css'
import type { ReactNode } from 'react'
import { Instrument_Serif, DM_Sans } from 'next/font/google';


const instrumentSerif = Instrument_Serif({
  weight: ['400'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--font-serif',
});

const dmSans = DM_Sans({
  weight: ['300', '400', '500', '600'],
  subsets: ['latin'],
  variable: '--font-sans',
});


export const metadata = {
  metadataBase: new URL('https://facelessstudio.ai'),
  title: {
    default: 'Faceless Studio — AI Content OS for YouTube Creators',
    template: '%s | Faceless Studio',
  },
  description:
    'Research trends, write scripts, generate scene breakdowns, and publish-ready content for your faceless YouTube channel — in 90 seconds. Built for Indian creators.',
  keywords: [
    'faceless youtube',
    'ai content generator',
    'youtube script writer',
    'ai youtube tool india',
    'faceless youtube automation',
    'content creator ai tool',
    'youtube hook generator',
    'ai scriptwriter',
    'hindi youtube content ai',
    'tamil youtube ai tool',
    'faceless channel tool',
    'youtube seo tool india',
  ],
  authors: [{ name: 'Faceless Studio' }],
  creator: 'Faceless Studio',
  openGraph: {
    type: 'website',
    locale: 'en_IN',
    url: 'https://facelessstudio.ai',
    siteName: 'Faceless Studio',
    title: 'Faceless Studio — AI Content OS for YouTube Creators',
    description:
      'From niche to upload-ready content pack in 90 seconds. Scripts, scenes, hooks, SEO, captions — all generated by AI. Free to start.',
    images: [
      {
        url: '/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'Faceless Studio — AI Content Operating System',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Faceless Studio — AI Content OS for YouTube Creators',
    description:
      'Research. Script. Scene. SEO. In 90 seconds. Free for Indian creators.',
    images: ['/og-image.jpg'],
    creator: '@facelessstudio',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: 'https://facelessstudio.ai',
  },
  verification: {
    google: 'YOUR_GOOGLE_VERIFICATION_CODE',
  },
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <meta name="theme-color" content="#0B1340" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />

        {/* Structured Data */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'SoftwareApplication',
              name: 'Faceless Studio',
              applicationCategory: 'BusinessApplication',
              operatingSystem: 'Web',
              description:
                'AI-powered content operating system for faceless YouTube creators.',
              offers: {
                '@type': 'Offer',
                price: '0',
                priceCurrency: 'INR',
                description: 'Free plan available',
              },
              aggregateRating: {
                '@type': 'AggregateRating',
                ratingValue: '4.8',
                reviewCount: '2300',
              },
            }),
          }}
        />
      </head>

      <body>{children}</body>
    </html>
  )
}